from __future__ import annotations

import base64
import hashlib
import json
from pathlib import Path

import pytest

from cmpct.reader import CMPCT
from cmpct.validation import preflight_archive


VECTORS = Path(__file__).with_name("conformance") / "v24-direct-codecs.json"


def _records() -> list[dict]:
    payload = json.loads(VECTORS.read_text())
    assert payload["schema"] == "cmpct-v24-golden-direct-codecs-v1"
    assert payload["format_revision"] == 24
    return payload["vectors"]


@pytest.mark.parametrize("record", _records(), ids=lambda r: r["name"])
def test_fixed_direct_codec_vector_is_byte_stable_and_readable(tmp_path: Path, record: dict) -> None:
    """Keep a non-builder-generated byte oracle for direct revision-24 codec interoperability.

    Footnote: these archives are committed as base64 so GitHub's text-only maintenance path cannot
    silently regenerate them from the Python builder. Their archive SHA is the golden boundary: if a
    reader refactor stops consuming these exact bytes, that is a conformance regression rather than
    an excuse to rewrite the fixture around the new implementation.
    """
    archive_bytes = base64.b64decode(record["archive_base64"], validate=True)
    assert len(archive_bytes) == record["archive_bytes"]
    assert hashlib.sha256(archive_bytes).hexdigest() == record["archive_sha256"]

    archive = tmp_path / f"golden-{record['codec']}.cmpct"
    archive.write_bytes(archive_bytes)

    summary = preflight_archive(archive)
    assert summary["version"] == 24
    assert summary["files"] == 1
    assert summary["blobs"] == 1

    expected_range = bytes.fromhex(record["range"]["hex"])
    with CMPCT(archive) as ar:
        row = ar.by[record["name"]]
        assert row[4] == record["logical_size"]
        assert row[6][0] == 0  # direct S_BLOB
        blob = ar.blobs[row[6][1]]
        assert blob[3] == record["codec"]
        raw = ar.read(record["name"])
        assert hashlib.sha256(raw).hexdigest() == record["logical_sha256"]
        assert ar.read_range(
            record["name"], record["range"]["offset"], record["range"]["length"]
        ) == expected_range


def test_golden_set_covers_current_direct_native_frontier() -> None:
    # RAW and Zstd are implemented in the native core; Deflate is deliberately included one step
    # ahead so its implementation can target fixed bytes instead of a Python-built archive.
    assert {record["codec"] for record in _records()} == {0, 1, 4}
