from __future__ import annotations

from pathlib import Path
import struct

import pytest

from experiments import entropygraph_v030_lattice as lattice


def test_lane_transform_has_independent_golden_vector() -> None:
    raw = b"abcdefghijklmnop"
    transformed = lattice.lane_forward(raw, 4)
    # Footnote: this vector is hand-derived from lane geometry, not generated by the inverse under test.
    # A writer and reader carrying the same indexing bug therefore cannot satisfy the oracle accidentally.
    assert transformed == b"aeimbfjncgkodhlp"
    assert lattice.lane_inverse(transformed, 4, len(raw)) == raw


def test_lane_transform_preserves_non_multiple_tail() -> None:
    raw = b"abcdefghijklmnopXYZ"
    transformed = lattice.lane_forward(raw, 4)
    assert transformed.endswith(b"XYZ")
    assert lattice.lane_inverse(transformed, 4, len(raw)) == raw


def test_lane_descriptor_rejects_unbounded_width() -> None:
    with pytest.raises(ValueError):
        lattice.lane_inverse(b"abcd", 32, 4)


def test_extraction_path_policy_rejects_traversal() -> None:
    for unsafe in ("../escape", "/absolute", "a/../escape", "a\\escape", ""):
        with pytest.raises(RuntimeError):
            lattice._safe_relpath(unsafe)
    assert lattice._safe_relpath("safe/nested/file.bin").as_posix() == "safe/nested/file.bin"


def test_lattice_graph_round_trips_and_selects_lane_nodes(tmp_path: Path) -> None:
    source = tmp_path / "source"
    source.mkdir()

    # Interleave a slowly changing high byte with a noisier low byte. This is deliberately a byte-level
    # construction rather than a .npy/type-specific fixture: the transform must discover entropy layout
    # from bytes alone.
    values = bytearray()
    for i in range(220_000):
        values.extend(struct.pack("<H", ((i * 73) ^ (i >> 5)) & 0x7FFF))
    (source / "numeric-like.bin").write_bytes(bytes(values))
    (source / "notes.txt").write_text(("lattice exact inverse proof\n" * 1200), encoding="utf-8")

    archive = tmp_path / "lattice.cmpct"
    stats = lattice._build_lattice(source, archive)
    assert stats["lane_nodes"] > 0
    assert stats["lane_payload_saving_bytes"] > 0
    assert stats["max_read_amplification"] == 1.0

    verified = lattice.strong_verify(archive)
    assert verified["ok"] is True
    assert verified["tree_sha256"] == lattice.treehash(source)

    restored = tmp_path / "restored"
    lattice.extract(archive, restored)
    assert lattice.treehash(restored) == lattice.treehash(source)


def test_balanced_chunks_never_exceed_inherited_ceiling() -> None:
    raw = bytes((i * 29) & 255 for i in range(lattice.MAX_CHUNK * 2 + 12345))
    chunks = lattice._balanced_chunks(raw)
    assert b"".join(chunks) == raw
    assert max(map(len, chunks)) <= lattice.MAX_CHUNK
    # The balancing rule exists to avoid one tiny trailing chunk and its reset/metadata tax.
    assert min(map(len, chunks)) >= len(raw) // len(chunks)
