from __future__ import annotations

"""Normalize durable EntropyGraph II evidence into the website's frontier payload.

Footnote: v0.28 now has three distinct benchmark questions and the public site must not collapse them:
(1) release delta — did v0.28 improve over its inherited v0.25 research base on fixed workloads?
(2) overall cross-format position — how does current v0.28 compare with external archive tools when
    each full public suite is archived as one matched recursive tree?
(3) category frontier — on each exact individual workload tree, where does current v0.28 beat or lose
    to a serious solid Zstandard size baseline, with ZIP/Deflate retained as a secondary familiar baseline?
The release delta is causal evidence, the whole-suite comparison is the arena, and the category record
powers the workload tiles. Canonical executable ZIP timing/size parity remains a fourth, separate site
surface generated by build_site.py.
"""

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
HISTORY = ROOT / "benchmarks" / "history"
SCHEMA = "cmpct-public-entropygraph-v028-benchmark-v1"
CATEGORY_SCHEMA = "cmpct-public-entropygraph-v028-category-v1"


def _pct_smaller(candidate: int, other: int) -> float | None:
    if other <= 0:
        return None
    return (other - candidate) / other * 100.0


def _latest_record() -> tuple[Path, dict[str, Any]] | None:
    matches: list[tuple[tuple[int, int, int], str, Path, dict[str, Any]]] = []
    for path in HISTORY.glob("*.json"):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if data.get("schema") != SCHEMA:
            continue
        try:
            version = tuple(int(x) for x in str(data.get("project_version", "0.0.0")).split("."))
        except ValueError:
            version = (0, 0, 0)
        matches.append(((version + (0, 0, 0))[:3], str(data.get("date") or ""), path, data))
    if not matches:
        return None
    _, _, path, data = max(matches, key=lambda row: (row[0], row[1], row[2].name))
    return path, data


def _latest_category_record(project_version: str | None) -> tuple[Path, dict[str, Any]] | None:
    matches: list[tuple[str, Path, dict[str, Any]]] = []
    for path in HISTORY.glob("*.json"):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if data.get("schema") != CATEGORY_SCHEMA:
            continue
        if str(data.get("project_version") or "") != str(project_version or ""):
            continue
        matches.append((str(data.get("date") or ""), path, data))
    if not matches:
        return None
    _, path, data = max(matches, key=lambda row: (row[0], row[1].name))
    return path, data


def _structural_snapshot(record: dict[str, Any]) -> dict[str, Any]:
    """Return matched whole-suite CMPCT and competitor totals.

    Footnote: structural competitors are measured on complete recursive trees. Their totals must
    therefore be compared with the CMPCT archives produced for those same complete trees, not with the
    sum of separately-created workload archives. Even a small aggregation mismatch can change
    deduplication/context opportunities and makes a headline percentage semantically wrong.
    """
    aliases = {
        "zip_deflate9": ("ZIP + Deflate-9", "ZIP / Deflate", "competitor"),
        "seven_zip_lzma2": ("7z + LZMA2", "7z / LZMA2", "competitor"),
        "zpaq_m5": ("ZPAQ method 5", "ZPAQ m5", "competitor"),
        "tar_zstd19_solid": ("solid tar + Zstandard-19 diagnostic", "tar / Zstd solid", "diagnostic"),
        "borg": ("Borg zstd backup repository", "Borg", "structural"),
        "dwarfs": ("DwarFS image", "DwarFS", "structural"),
    }
    structural = record.get("structural_competitors") or {}
    suites = list(structural.get("rows") or [])
    if not suites:
        return {
            "candidate_bytes": 0,
            "logical_bytes": 0,
            "files": 0,
            "competitors": [],
            "method": structural.get("method") or {},
        }

    candidate_total = 0
    logical_total = 0
    files_total = 0
    candidate_seen = 0
    totals = {key: 0 for key in aliases}
    seen = {key: 0 for key in aliases}

    for suite in suites:
        if isinstance(suite.get("cmpct_bytes"), int):
            candidate_total += int(suite["cmpct_bytes"])
            candidate_seen += 1
        logical_total += int(suite.get("logical_bytes") or 0)
        files_total += int(suite.get("files") or 0)
        for key in aliases:
            cell = (suite.get("competitors") or {}).get(key) or {}
            if cell.get("available") and isinstance(cell.get("bytes"), int):
                totals[key] += int(cell["bytes"])
                seen[key] += 1

    # Footnote: a public combined bar is emitted only when both the candidate and the competitor were
    # measured across every structural suite. Partial totals look impressively small for the wrong reason.
    if candidate_seen != len(suites):
        candidate_total = 0

    competitors: list[dict[str, Any]] = []
    if candidate_total:
        competitors.append(
            {
                "name": "CMPCT EntropyGraph II matched aggregate",
                "short": "CMPCT v0.28",
                "bytes": candidate_total,
                "lead_pct": 0.0,
                "role": "candidate",
            }
        )
        for key, (name, short, role) in aliases.items():
            if seen[key] != len(suites):
                continue
            size = totals[key]
            competitors.append(
                {
                    "name": name,
                    "short": short,
                    "bytes": size,
                    "lead_pct": _pct_smaller(candidate_total, size),
                    "role": role,
                }
            )

    return {
        "candidate_bytes": candidate_total,
        "logical_bytes": logical_total,
        "files": files_total,
        "suite_count": len(suites),
        "competitors": competitors,
        "method": structural.get("method") or {},
    }


def _category_snapshot(project_version: str | None, frontier_rows: list[dict[str, Any]]) -> dict[str, Any]:
    found = _latest_category_record(project_version)
    if found is None:
        return {}
    path, record = found
    contract = record.get("benchmark_contract") or record.get("contract") or {}
    rows = list(record.get("rows") or [])
    by_key = {(str(row.get("suite") or ""), str(row.get("name") or "")): row for row in rows}
    expected = {(str(row.get("suite") or ""), str(row.get("name") or "")) for row in frontier_rows}

    # Footnote: category boasting is all-or-nothing and accepts only the benchmark contract that measured
    # CMPCT and both external baselines during the same generated-tree lifetime. Some valid synthetic
    # producer formats can embed run-varying metadata, so a fresh category run need not reproduce an old
    # release-delta tree hash. The category record's own tree hash proves the three archives in that row
    # shared one tree; the workload-key set proves that the record covers the current frontier scope.
    if contract.get("same_lifetime_measurement") is not True:
        return {}
    if len(by_key) != len(rows) or set(by_key) != expected:
        return {}

    normalized_rows: list[dict[str, Any]] = []
    for source in frontier_rows:
        key = (str(source.get("suite") or ""), str(source.get("name") or ""))
        row = by_key[key]
        candidate = int(row.get("cmpct_bytes") or 0)
        zstd = int(row.get("tar_zstd19_solid_bytes") or 0)
        zip_bytes = int(row.get("zip_deflate9_bytes") or 0)
        tree_sha256 = str(row.get("tree_sha256") or "")
        if candidate <= 0 or zstd <= 0 or zip_bytes <= 0 or not tree_sha256:
            return {}
        normalized_rows.append(
            {
                "suite": key[0],
                "name": key[1],
                "files": int(row.get("files") or source.get("files") or 0),
                "logical_bytes": int(row.get("logical_bytes") or source.get("logical_bytes") or 0),
                "tree_sha256": tree_sha256,
                "cmpct_bytes": candidate,
                "zstd_bytes": zstd,
                "zip_deflate_bytes": zip_bytes,
                "cmpct_vs_zstd_pct": _pct_smaller(candidate, zstd),
                "cmpct_vs_zip_deflate_pct": _pct_smaller(candidate, zip_bytes),
            }
        )

    candidate_total = sum(row["cmpct_bytes"] for row in normalized_rows)
    zstd_total = sum(row["zstd_bytes"] for row in normalized_rows)
    zip_total = sum(row["zip_deflate_bytes"] for row in normalized_rows)
    return {
        "file": path.name,
        "date": record.get("date"),
        "baseline_short": "tar / Zstd solid",
        "baseline_name": "solid tar + Zstandard-19",
        "secondary_short": "ZIP / Deflate",
        "candidate_bytes": candidate_total,
        "zstd_bytes": zstd_total,
        "zip_deflate_bytes": zip_total,
        "lead_vs_zstd_pct": _pct_smaller(candidate_total, zstd_total),
        "lead_vs_zip_deflate_pct": _pct_smaller(candidate_total, zip_total),
        "workloads": len(normalized_rows),
        "wins_vs_zstd": sum(row["cmpct_bytes"] < row["zstd_bytes"] for row in normalized_rows),
        "losses_vs_zstd": sum(row["cmpct_bytes"] > row["zstd_bytes"] for row in normalized_rows),
        "ties_vs_zstd": sum(row["cmpct_bytes"] == row["zstd_bytes"] for row in normalized_rows),
        "rows": normalized_rows,
        "contract": contract,
    }


def normalize(path: Path, record: dict[str, Any]) -> dict[str, Any]:
    totals = record.get("totals") or {}
    release_candidate = int(totals.get("candidate_bytes") or 0)
    inherited = int(totals.get("inherited_v025_bytes") or 0)
    rows = list(record.get("rows") or [])
    logical = sum(int(row.get("logical_bytes") or 0) for row in rows)
    files = sum(int(row.get("files") or 0) for row in rows)
    structural = _structural_snapshot(record)
    category = _category_snapshot(record.get("project_version"), rows)
    category_by_key = {
        (str(row.get("suite") or ""), str(row.get("name") or "")): row
        for row in list(category.get("rows") or [])
    }

    workloads = []
    for row in rows:
        current = int(row.get("candidate_bytes") or 0)
        base = int(row.get("inherited_v025_bytes") or 0)
        key = (str(row.get("suite") or ""), str(row.get("name") or ""))
        external = category_by_key.get(key) or {}
        workloads.append(
            {
                **row,
                "cmpct_vs_primary_pct": _pct_smaller(current, base),
                "improved": current < base,
                "fallback": row.get("selected") != "resemblance",
                "category_zstd_bytes": external.get("zstd_bytes"),
                "category_zip_deflate_bytes": external.get("zip_deflate_bytes"),
                "cmpct_vs_zstd_pct": external.get("cmpct_vs_zstd_pct"),
                "cmpct_vs_zip_deflate_pct": external.get("cmpct_vs_zip_deflate_pct"),
            }
        )

    primary_lead = _pct_smaller(release_candidate, inherited)
    matched_candidate = int(structural.get("candidate_bytes") or 0)
    matched_logical = int(structural.get("logical_bytes") or logical)
    matched_files = int(structural.get("files") or files)
    matched_competitors = list(structural.get("competitors") or [])

    # ZIP/Deflate stays the familiar headline comparator while solid Zstd is elevated beside it as the
    # serious compression baseline. The full ladder keeps stronger archival competitors visible too.
    headline_short = "ZIP / Deflate"
    if not any(row.get("short") == headline_short for row in matched_competitors):
        headline_short = next(
            (str(row.get("short")) for row in matched_competitors if row.get("role") == "competitor"),
            "",
        )

    return {
        "file": path.name,
        "date": record.get("date"),
        "kind": "research-frontier",
        "schema": SCHEMA,
        "render_contract": "entropygraph-v028",
        "project_version": record.get("project_version"),
        "canonical_format_revision": record.get("canonical_format_revision"),
        "candidate": record.get("candidate") or {},
        "contract": record.get("benchmark_contract") or {},
        # Footnote: top-level bytes/competitors are the matched whole-suite cross-format view because
        # app.js uses these fields for the public arena. Release and category evidence live separately.
        "logical_bytes": matched_logical,
        "files": matched_files,
        "workload_count": len(workloads),
        "archive_bytes": matched_candidate,
        "ratio": matched_candidate / matched_logical if matched_logical else None,
        "saved_pct": _pct_smaller(matched_candidate, matched_logical),
        "competitors": matched_competitors,
        "overall_comparison": {
            "candidate_bytes": matched_candidate,
            "logical_bytes": matched_logical,
            "files": matched_files,
            "suite_count": structural.get("suite_count") or 0,
            "headline_comparator_short": headline_short,
            "serious_comparator_short": "tar / Zstd solid",
            "competitors": matched_competitors,
            "method": structural.get("method") or {},
        },
        "category_comparison": category,
        "release_delta": {
            "candidate_bytes": release_candidate,
            "baseline_bytes": inherited,
            "baseline_short": "EntropyGraph v0.25",
            "lead_pct": primary_lead,
            "workloads": len(workloads),
            "workloads_improved": int(totals.get("workloads_improved") or 0),
            "workloads_regressed": int(totals.get("workloads_regressed") or 0),
            "resemblance_selected": int(totals.get("resemblance_selected") or 0),
        },
        # Compatibility fields retained for release-gate tooling and historical readers.
        "primary_comparator": {
            "short": "EntropyGraph v0.25",
            "name": "inherited EntropyGraph v0.25 frontier",
            "bytes": inherited,
            "lead_pct": primary_lead,
        },
        "wins_primary": int(totals.get("workloads_improved") or 0),
        "regressions_primary": int(totals.get("workloads_regressed") or 0),
        "resemblance_selected": int(totals.get("resemblance_selected") or 0),
        "delta_nodes": int(totals.get("delta_nodes") or 0),
        "preflate_wins": int(totals.get("preflate_wins") or 0),
        "workloads": workloads,
        "known_losses": record.get("known_limits") or [],
        "structural_competitor_contract": structural.get("method") or {},
    }


def patch_project_data(output: Path) -> bool:
    found = _latest_record()
    path = output / "project-data.json"
    if found is None or not path.exists():
        return False
    record_path, record = found
    frontier = normalize(record_path, record)
    payload = json.loads(path.read_text(encoding="utf-8"))
    history = [
        row
        for row in list(payload.get("frontier_history") or [])
        if row.get("project_version") != frontier.get("project_version")
    ]
    history.insert(0, frontier)
    payload["frontier"] = frontier
    payload["frontier_history"] = history
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return True