//! Exact revision-24 Deflate stream-mode-2 regeneration.
//!
//! Mode 2 records authenticated logical content plus the zlib compression level and expects the
//! original raw RFC-1951 stream to be regenerated byte-for-byte. A generic Deflate encoder is not a
//! sufficient contract: equivalent streams can differ at the byte level and would therefore alter the
//! enclosing virtual ZIP. On Unix-family targets (including Android and Apple platforms) this module
//! calls the platform zlib ABI with the same raw-stream parameters used by Python's
//! `zlib.compressobj(level, Z_DEFLATED, -15)`.
//!
//! Windows does not guarantee a stock zlib ABI as part of the operating system. The module therefore
//! returns a typed `Unavailable` there rather than silently falling back to a non-bit-identical encoder.
//! A Windows package may later provide the same stock-zlib ABI as part of the native SDK without
//! changing revision-24 bytes.

use std::os::raw::{c_char, c_int, c_uint, c_ulong, c_void};
use thiserror::Error;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum DeflateRegenError {
    #[error("stock zlib regeneration backend is unavailable on this target")]
    Unavailable,
    #[error("Deflate regeneration input/output exceeds the native handler resource limit")]
    ResourceLimit,
    #[error("recorded zlib level is outside revision-24 range 0..=9")]
    Level,
    #[error("zlib failed to regenerate the raw RFC-1951 stream")]
    Encode,
    #[error("regenerated Deflate stream length disagrees with the authenticated recipe")]
    StreamLength,
    #[error("requested regenerated Deflate range is outside the exact stream")]
    Range,
}

#[cfg(unix)]
mod ffi {
    use super::*;

    pub const Z_DEFLATED: c_int = 8;
    pub const Z_DEFAULT_STRATEGY: c_int = 0;
    pub const Z_FINISH: c_int = 4;
    pub const Z_STREAM_END: c_int = 1;

    pub type AllocFn = unsafe extern "C" fn(*mut c_void, c_uint, c_uint) -> *mut c_void;
    pub type FreeFn = unsafe extern "C" fn(*mut c_void, *mut c_void);

    #[repr(C)]
    pub struct ZStream {
        pub next_in: *mut u8,
        pub avail_in: c_uint,
        pub total_in: c_ulong,
        pub next_out: *mut u8,
        pub avail_out: c_uint,
        pub total_out: c_ulong,
        pub msg: *mut c_char,
        pub state: *mut c_void,
        pub zalloc: Option<AllocFn>,
        pub zfree: Option<FreeFn>,
        pub opaque: *mut c_void,
        pub data_type: c_int,
        pub adler: c_ulong,
        pub reserved: c_ulong,
    }

    impl Default for ZStream {
        fn default() -> Self {
            Self {
                next_in: std::ptr::null_mut(),
                avail_in: 0,
                total_in: 0,
                next_out: std::ptr::null_mut(),
                avail_out: 0,
                total_out: 0,
                msg: std::ptr::null_mut(),
                state: std::ptr::null_mut(),
                zalloc: None,
                zfree: None,
                opaque: std::ptr::null_mut(),
                data_type: 0,
                adler: 0,
                reserved: 0,
            }
        }
    }

    #[link(name = "z")]
    extern "C" {
        #[link_name = "zlibVersion"]
        pub fn zlib_version() -> *const c_char;
        #[link_name = "deflateInit2_"]
        pub fn deflate_init2(
            stream: *mut ZStream,
            level: c_int,
            method: c_int,
            window_bits: c_int,
            mem_level: c_int,
            strategy: c_int,
            version: *const c_char,
            stream_size: c_int,
        ) -> c_int;
        #[link_name = "deflateBound"]
        pub fn deflate_bound(stream: *mut ZStream, source_len: c_ulong) -> c_ulong;
        pub fn deflate(stream: *mut ZStream, flush: c_int) -> c_int;
        #[link_name = "deflateEnd"]
        pub fn deflate_end(stream: *mut ZStream) -> c_int;
    }
}

#[cfg(unix)]
fn regenerate(raw: &[u8], level: u8, max_object_bytes: u64) -> Result<Vec<u8>, DeflateRegenError> {
    use ffi::*;

    if level > 9 {
        return Err(DeflateRegenError::Level);
    }
    if raw.len() as u64 > max_object_bytes || raw.len() > c_uint::MAX as usize {
        return Err(DeflateRegenError::ResourceLimit);
    }

    let mut stream = ZStream::default();
    let init = unsafe {
        deflate_init2(
            &mut stream,
            level as c_int,
            Z_DEFLATED,
            -15, // raw RFC-1951, no zlib/gzip framing
            8,   // zlib default memLevel used by Python compressobj
            Z_DEFAULT_STRATEGY,
            zlib_version(),
            std::mem::size_of::<ZStream>() as c_int,
        )
    };
    if init != 0 {
        return Err(DeflateRegenError::Encode);
    }

    let result = (|| {
        let bound = unsafe { deflate_bound(&mut stream, raw.len() as c_ulong) };
        let bound = usize::try_from(bound).map_err(|_| DeflateRegenError::ResourceLimit)?;
        if bound as u64 > max_object_bytes || bound > c_uint::MAX as usize {
            return Err(DeflateRegenError::ResourceLimit);
        }
        let mut out = vec![0u8; bound.max(1)];
        stream.next_in = raw.as_ptr() as *mut u8;
        stream.avail_in = raw.len() as c_uint;
        stream.next_out = out.as_mut_ptr();
        stream.avail_out = out.len() as c_uint;

        let status = unsafe { deflate(&mut stream, Z_FINISH) };
        if status != Z_STREAM_END {
            return Err(DeflateRegenError::Encode);
        }
        let written =
            usize::try_from(stream.total_out).map_err(|_| DeflateRegenError::ResourceLimit)?;
        if written > out.len() {
            return Err(DeflateRegenError::Encode);
        }
        out.truncate(written);
        Ok(out)
    })();

    // Footnote: always release zlib state, including after resource-limit or stream failures. The
    // native core may service many range requests in a long-lived document provider process.
    unsafe {
        let _ = deflate_end(&mut stream);
    }
    result
}

#[cfg(not(unix))]
fn regenerate(
    _raw: &[u8],
    _level: u8,
    _max_object_bytes: u64,
) -> Result<Vec<u8>, DeflateRegenError> {
    Err(DeflateRegenError::Unavailable)
}

/// Regenerate and copy one exact mode-2 raw-Deflate range.
///
/// `expected_stream_len` comes from authenticated recipe metadata. The complete stream is regenerated
/// before slicing so a partial caller can never receive bytes from an encoder invocation that already
/// disagrees with the fixed stream length contract.
pub fn exact_range(
    raw: &[u8],
    level: u8,
    expected_stream_len: u64,
    start: u64,
    out: &mut [u8],
    max_object_bytes: u64,
) -> Result<(), DeflateRegenError> {
    if expected_stream_len > max_object_bytes {
        return Err(DeflateRegenError::ResourceLimit);
    }
    let stream = regenerate(raw, level, max_object_bytes)?;
    if stream.len() as u64 != expected_stream_len {
        return Err(DeflateRegenError::StreamLength);
    }
    let end = start
        .checked_add(u64::try_from(out.len()).map_err(|_| DeflateRegenError::Range)?)
        .ok_or(DeflateRegenError::Range)?;
    if end > expected_stream_len {
        return Err(DeflateRegenError::Range);
    }
    let start = usize::try_from(start).map_err(|_| DeflateRegenError::Range)?;
    let end = start
        .checked_add(out.len())
        .ok_or(DeflateRegenError::Range)?;
    out.copy_from_slice(&stream[start..end]);
    Ok(())
}
